### ISSUE TITLE
Dropdown Menu: list item onSelect is fired sometimes during onClick of the trigger

### ISSUE THREAD

**Issue by kyle-platt** [radix-ui/design-system#305]
Sometimes when clicking the trigger to open the dropdown menu list, the onSelect of the 1st or 2nd item in the list is called. This updates the value selected and closes the list immediately. 

Expected Result: A click on the trigger button should only open or close the menu list.

Current Outcome: Some clicks on the trigger button cause the onSelect of an item to be triggered.

https://user-images.githubusercontent.com/24979594/109700871-52bb1000-7b60-11eb-9cb1-76913d598f79.mov

**Comment by peduarte** [comment]
Hmm! Thanks for raising this. We have a [big PR](https://github.com/radix-ui/design-system/pull/300) on the way so I'll see if I can address it there

**Comment by kyle-platt** [comment]
Okay great to hear. Thanks!

**Comment by kyle-platt** [comment]
Hey @peduarte It looks like that PR was merged. Did anyone get the chance to address this?

**Comment by peduarte** [comment]
@kyle-platt I've had to take some time off, but pinging @benoitgrelard to assist.

**Comment by benoitgrelard** [comment]
Hey @kyle-platt I've been trying to reproduce what you're seeing but haven't been able to.
Here's a sandbox with our design system's `DropdownMenu`:

**Comment by kyle-platt** [comment]
Hey @benoitgrelard here's our component stripped down a bit. Happy to help on this. Let me know if you have any questions or concerns. https://codesandbox.io/s/radix-dropdown-example-gv28o

**Comment by benoitgrelard** [comment]
A few thoughts:

- it seems you are using the primitives, not the design system, so your issue is in the wrong repo. it should be here instead: https://github.com/radix-ui/primitives
- I still can't seem to reproduce the issue on your sandbox.
- On another note, you are trying to create a **select** out of a **dropdown menu**. You really shouldn't be doing as these are inherently different wai-aria patterns and thus will cause accessibility issues.

We will soon have a `Select` primitive which is the correct pattern for what you are trying to achieve.

**Comment by kyle-platt** [comment]
@benoitgrelard thank you for the helpful insight. My apologies for the wrong repo. I also wasn't aware of the difference between a `select` and a `dropdown menu`. I look forward to playing around with the `Select` primitive once that's released!

**Comment by benoitgrelard** [comment]
Hey @kyle-platt, we have been able to reproduce the issue in a simplified setup.
It seems it's a very particular set of circumstances that produces it.
I've created an issue on the primitives side: https://github.com/radix-ui/primitives/issues/540

Thanks for bringing this to our attention! 🙏
